### ISSUE TITLE
line 1383: @: unbound variable

### ISSUE THREAD

**Issue by MagePsycho** [yvoronoy/m2install#114]
In Macbook Pro 10.11.6, I am getting this error:

> line 1383: @: unbound variable

Is the script not compatible with Darwin distro?

**Comment by yvoronoy** [comment]
It should under darwin, because I'm using it on my MacOSX

could you please specify your 
 - Bash version
 - OS version

**Comment by yvoronoy** [comment]
It has to be fixed in master now because I've removed strict mode
https://github.com/yvoronoy/m2install/commit/551ab051ed0cba3168b4165ea3f590301da22333
