### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by happycoffeebean** [yvoronoy/m2install#130]
root@ubuntu-2gb-nyc3-pure:/var/www/html# sh m2install.sh -s git
m2install.sh: 62: m2install.sh: Syntax error: "(" unexpected

**Comment by yvoronoy** [comment]
@happycoffeebean thank you for reporting.
It's because you are trying to use sh. try $ bash m2install.sh
or just give access chmod +x m2install.sh and just run $ m2install.sh

**Comment by happycoffeebean** [comment]
Thank you for your fast response.  Unfortunately, neither of those works for me, and I'm not sure why.  I've worked extensively with Debian, but not Ubuntu, so I'm not sure what the differences are (I didn't think there were many).   I'm not sure why I'm getting a composer error, when I followed the non-composer instructions. 

==== Output ====
root@ubuntu-2gb-nyc3-pure:/var/www/html# chmod +x m2install.sh                 
root@ubuntu-2gb-nyc3-pure:/var/www/html# m2install.sh
m2install.sh: command not found
root@ubuntu-2gb-nyc3-pure:/var/www/html# bash m2install.sh
Current Directory: /var/www/html
Configuration loaded from: /root/.m2install.conf /root/.m2install.conf.override  ./.m2install.conf
Error: 'composer' is not found on this system
root@ubuntu-2gb-nyc3-pure:/var/www/html#

**Comment by happycoffeebean** [comment]
Thank you for the quick reply.  Now, even though I specified git, it's still trying to install with composer:
---
root@ubuntu-2gb-nyc3-pure:/var/www/html# ./m2install.sh -s git
Current Directory: /var/www/html
Configuration loaded from: /root/.m2install.conf /root/.m2install.conf.override  ./.m2install.conf
Error: 'composer' is not found on this system

**Comment by yvoronoy** [comment]
That's right, because it's suppose you should have composer tool to install magento. Magento manage dependencies through composer.
Here is the guide how to install it http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install_composer.html
