### ISSUE TITLE
Installs a different version without a warning

### ISSUE THREAD

**Issue by katmoon** [yvoronoy/m2install#133]
I tried to install using this command from magento-sparta repo:
`m2install.sh -s git --git-branch 2.1.11 --sample-data yes --ee -f`
The installation finished successfully and only after I've finished testing, I've noticed that it installed `develop` branch instead (because there was no 2.1.11 branch).
Please break installation if the branch has not been found rather then installing develop branch.

**Comment by yvoronoy** [comment]
Thank you, Katerina
Fixed, merged 
You can use -v instead of --git-branch everytime for git or composer
m2install.sh -s git -v 2.1.11 --sample-data yes --ee -f
or 
m2install.sh -s composer -v 2.1.11 -f

**Comment by katmoon** [comment]
Thank you @yvoronoy
