### ISSUE TITLE
The getTablePrefix() fails on 2.2.4 with the new array declaration

### ISSUE THREAD

**Issue by yyevgenii** [yvoronoy/m2install#144]
Prior to 2.2.4 the table_prefix in the env.php ended with a coma:
```
    'table_prefix' => '',
```
while the 2.2.4 wit the new array declaration don't require the coma anymore:
```
    'table_prefix' => ''
```

This lead to the failure of `configure_db` step, because getTablePrefix() returns single quote character as the table prefix:
```
$ grep table_prefix ee224/app/etc/env.php
    'table_prefix' => ''
$ grep table_prefix ee224/app/etc/env.php | head -n1 | sed "s/[a-z'_ ]*[=][>][ ]*[']//" | sed "s/['][,]//"
'
```

The following function should be reworked:
```
function getTablePrefix()
{
    echo $(grep 'table_prefix' app/etc/env.php | head -n1 | sed "s/[a-z'_ ]*[=][>][ ]*[']//" | sed "s/['][,]//")
    return 0;
}
```

**Comment by yvoronoy** [comment]
Thank you @yyevgenii 
Merged (/)
