### ISSUE TITLE
Add check required tools

### ISSUE THREAD

**Issue by yvoronoy** [yvoronoy/m2install#46]
Script should check required tools and throw error if there is no required tools:
- php
- composer
- mysql
- mysqladmin
- git
- printf
- echo
- cat
- basename
- pwd
- tar
- gunzip
- sed
- tr
- grep
- mkdir
- wget
- cp
- mv
- rm
- find
- chmod
- date
- expr

**Comment by yyevgenii** [comment]
I've added check for the following utils:
* php
* composer
* mysql
* mysqladmin
* git
* cat
* basename
* tar
* gunzip
* sed
* tr
* grep 
* mkdir
* wget 
* cp
* mv
* rm
* find 
* chmod
* date 

The rest of commands are bash builtins:
* printf
* echo
* pwd
* expr
