### ISSUE TITLE
URGENT!!! Custom admin path

### ISSUE THREAD

**Issue by isitnikov** [yvoronoy/m2install#71]
After deploying I can access admin panel (get 404) because admin/url/custom_path is not empty and admin/url/use_custom_path = 1.

Please, fix it ASAP!!!!

**Comment by akiseliov** [comment]
![ASAAAAP](http://i3.kym-cdn.com/entries/icons/original/000/000/026/Gerard-Butler-This-Is-Sparta.jpg)

ASAAAAAP!!!

**Comment by yvoronoy** [comment]
Don't worry guys, I'll fix it ASAP!!!!!!
![Dont Worry](https://cdn.meme.am/instances/34635565.jpg)

**Comment by isitnikov** [comment]
![s](https://s-media-cache-ak0.pinimg.com/564x/b9/6e/be/b96ebe9121b42362a63921caf08bd84b.jpg)

**Comment by isitnikov** [comment]
![Thank you](https://static2.fjcdn.com/comments/I+thank+you+for+your+service+would+it+be+a+_672816d98254c08f86aa8ccdf1cf868a.jpg)
