### ISSUE TITLE
Failure during installation on OS X

### ISSUE THREAD

**Issue by magicbunneh** [yvoronoy/m2install#89]
find ./pub  -type l -! -exec test -e {} \; -print | xargs --no-run-if-empty unlink
find: -!: unknown primary or operator
xargs: illegal option -- -

**Comment by yvoronoy** [comment]
I use OSX and doesn't have such issue.
Could you provide more details? Bash version & OSX version.

@iskliarenko please take a look, what is wrong in this syntax

**Comment by magicbunneh** [comment]
System Version: OS X 10.11.5 (15F34)
Kernel Version: Darwin 15.5.0
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

**Comment by yvoronoy** [comment]
@magicbunneh could you check this construction on your system?
`find -L ./ -type l -delete;`
If it works, I'll merge it

**Comment by magicbunneh** [comment]
Seems to work.

**Comment by yvoronoy** [comment]
@magicbunneh merged, thank you
